// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/gossip.proto

package gossip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_proto_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_proto_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metadata) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Keys          map[string]*Metadata   `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_proto_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncRequest) GetKeys() map[string]*Metadata {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the requester is missing keys or has older versions, the responder sends the full values back
	Updates       map[string]*Value `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_proto_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *SyncResponse) GetUpdates() map[string]*Value {
	if x != nil {
		return x.Updates
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_proto_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_proto_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Value) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Value) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_api_proto_gossip_proto protoreflect.FileDescriptor

const file_api_proto_gossip_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/gossip.proto\x12\x06gossip\"B\n" +
	"\bMetadata\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\xa4\x01\n" +
	"\vSyncRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\x04keys\x18\x02 \x03(\v2\x1d.gossip.SyncRequest.KeysEntryR\x04keys\x1aI\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.gossip.MetadataR\x05value:\x028\x01\"\x96\x01\n" +
	"\fSyncResponse\x12;\n" +
	"\aupdates\x18\x01 \x03(\v2!.gossip.SyncResponse.UpdatesEntryR\aupdates\x1aI\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.gossip.ValueR\x05value:\x028\x01\"S\n" +
	"\x05Value\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted2B\n" +
	"\rGossipService\x121\n" +
	"\x04Sync\x12\x13.gossip.SyncRequest\x1a\x14.gossip.SyncResponseB-Z+github.com/shivang/kvstore/api/proto/gossipb\x06proto3"

var (
	file_api_proto_gossip_proto_rawDescOnce sync.Once
	file_api_proto_gossip_proto_rawDescData []byte
)

func file_api_proto_gossip_proto_rawDescGZIP() []byte {
	file_api_proto_gossip_proto_rawDescOnce.Do(func() {
		file_api_proto_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gossip_proto_rawDesc), len(file_api_proto_gossip_proto_rawDesc)))
	})
	return file_api_proto_gossip_proto_rawDescData
}

var file_api_proto_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_gossip_proto_goTypes = []any{
	(*Metadata)(nil),     // 0: gossip.Metadata
	(*SyncRequest)(nil),  // 1: gossip.SyncRequest
	(*SyncResponse)(nil), // 2: gossip.SyncResponse
	(*Value)(nil),        // 3: gossip.Value
	nil,                  // 4: gossip.SyncRequest.KeysEntry
	nil,                  // 5: gossip.SyncResponse.UpdatesEntry
}
var file_api_proto_gossip_proto_depIdxs = []int32{
	4, // 0: gossip.SyncRequest.keys:type_name -> gossip.SyncRequest.KeysEntry
	5, // 1: gossip.SyncResponse.updates:type_name -> gossip.SyncResponse.UpdatesEntry
	0, // 2: gossip.SyncRequest.KeysEntry.value:type_name -> gossip.Metadata
	3, // 3: gossip.SyncResponse.UpdatesEntry.value:type_name -> gossip.Value
	1, // 4: gossip.GossipService.Sync:input_type -> gossip.SyncRequest
	2, // 5: gossip.GossipService.Sync:output_type -> gossip.SyncResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_gossip_proto_init() }
func file_api_proto_gossip_proto_init() {
	if File_api_proto_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gossip_proto_rawDesc), len(file_api_proto_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gossip_proto_goTypes,
		DependencyIndexes: file_api_proto_gossip_proto_depIdxs,
		MessageInfos:      file_api_proto_gossip_proto_msgTypes,
	}.Build()
	File_api_proto_gossip_proto = out.File
	file_api_proto_gossip_proto_goTypes = nil
	file_api_proto_gossip_proto_depIdxs = nil
}
